### ISSUE TITLE
Boot Failing, OpenCore 0.6.1

### ISSUE THREAD

**Issue by arrmo** [Leoyzen/KVM-Opencore#17]
Hi,

I realize that your configuration and config.plist are for 0.5.6 (right?), but I assume the intention is to somewhat keep up with OpenCore (given bug fixes, new features, etc.)? I tried the current config.plist with 0.6.1, and it fails to boot. Not fully unexpected, guessing there is some incompatible setting. Is there a good way to capture debug / log information, to work through this?

But also, is there a "minimum" config.plist, that can be used across different OpenCore versions? Not fully optimized of course, but enough to "crawl before walk" 😄. I thought I had seen one a while back, all that is required to boot and keep iServices happy, but I could surely be wrong. I (think I) have the needed basic information (from my old laptop with a dead screen), but very likely some kvm setting is causing the non-boot issue (in 0.6.1).

Thanks!

**Comment by eljojo** [comment]
@arrmo did you get this to work?

**Comment by thenickdude** [comment]
My fork is updated to 0.6.3, you can probably draw configuration from that instead: https://github.com/thenickdude/KVM-Opencore

**Comment by arrmo** [comment]
Will give that a try, thanks! I'll close this open item, as it's not really applicable here I guess (i.e. this repository is for an older version of OC it seems).

Thanks again.
