### ISSUE TITLE
opencore can't find apfs disk using latest/stock OVMF.

### ISSUE THREAD

**Issue by Leoyzen** [Leoyzen/KVM-Opencore#3]
ref: https://github.com/acidanthera/bugtracker/issues/751
We can now just using apfs-nolog.efi extracted from latest MacOS instead of ApfsDriverLoader until the rewrite is done.

**Comment by Leoyzen** [comment]
fixed

**Comment by thenickdude** [comment]
With latest OC master I also had to set MinDate=-1 and MinVersion=-1 in the APFS section for my (slightly outdated) Catalina install to appear on the boot menu, I think the default minimums were a little too strict.
