### ISSUE TITLE
Unplugging USB device freezes MacOS

### ISSUE THREAD

**Issue by emilevirus** [Leoyzen/KVM-Opencore#7]
I have passed through a USB hub (acts as a switch) where I connect my keyboard and mouse to switch between my PC and my VM. VM completely freezes when I press ‘switch’ (keyboard and mouse are disconnected). The first time switching doesn't make it freeze, but 2nd time, yes.

**Comment by Acelogic** [comment]
List your specs

**Comment by emilevirus** [comment]
Nevermind, it's an hypervisor bug
